# List of object enabled for picking & placing
# model: gazebo model id
# default_link: gazebo link used for picking for default

objects:
 -
  model: rb1_simple_cart
  default_link: link_0
robots:
-
  model: robot
  default_link: robot_base_footprint
  elevation_z: 0.05
-
  model: robot_b
  default_link: robot_b_base_footprint
  elevation_z: 0.05
-
  model: robot_c
  default_link: robot_c_base_footprint
  elevation_z: 0.05

config:
 # min distance for the simple pick
 min_picking_distance: 0.1
